# Generated by Django 4.1.5 on 2023-01-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
